# Numpy
Numpy is at the core of scientific computing in python. It provides containers for numerical arrays in computing memory and basic to advanced array manipulation routines, such as pointwise operations, but also matrix multiplications and decompositions. It is designed for efficient **array-oriented computing**

In [2]:
import numpy as np

Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 26 days


In [4]:
X = np.random.randn(3, 5)
print X

[[-0.05199373 -1.27031501 -2.01749499  0.46799571 -1.20234413]
 [-0.66353157  0.44764524  0.65576448  0.38230002 -0.48073244]
 [ 0.9325603   0.01567161  1.48827167 -0.16287019 -1.58845233]]


Looks like a list of lists. And indeed, if we use a single index into the array, we will obtain rows:

In [5]:
X[0]

array([-0.05199373, -1.27031501, -2.01749499,  0.46799571, -1.20234413])

In [6]:
X[0, 1]

-1.2703150105949943

In [7]:
X[0, 0:2]

array([-0.05199373, -1.27031501])

In [8]:
X[0, 0:None]

array([-0.05199373, -1.27031501, -2.01749499,  0.46799571, -1.20234413])

In [9]:
X[0, :]

array([-0.05199373, -1.27031501, -2.01749499,  0.46799571, -1.20234413])

In [10]:
X[:, 0]

array([-0.05199373, -0.66353157,  0.9325603 ])

## Pointwise operations

In [18]:
a = np.arange(100)

In [19]:
a ** 2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [20]:
2 * a

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [21]:
a + 1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [23]:
b = np.zeros_like(a)
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
b[0] = 1
b

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
a + b

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Using lists for this would be much slower

In [27]:
L = range(100)

In [28]:
%timeit [i ** 2 for i in L]

The slowest run took 5.67 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 10.8 µs per loop


In [29]:
%timeit a ** 2

The slowest run took 47.78 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 714 ns per loop


## Matrix multiplication
Contrary to matlab defaults, the **"*"**-operator is pointwise multiplication (in matlab it is matrix multiplication). Matrix multiplication is done with `np.dot`

In [30]:
Y = np.random.randn(5, 4)

In [31]:
X, Y

(array([[-0.05199373, -1.27031501, -2.01749499,  0.46799571, -1.20234413],
        [-0.66353157,  0.44764524,  0.65576448,  0.38230002, -0.48073244],
        [ 0.9325603 ,  0.01567161,  1.48827167, -0.16287019, -1.58845233]]),
 array([[ 2.01596208,  0.21241268, -1.02793462, -0.68280268],
        [-0.12565588,  0.63898147, -0.60971913, -0.12127546],
        [ 1.50399573, -0.49686611, -1.16951062, -0.08914925],
        [-0.34710659, -1.68030252,  1.14634621,  1.81467219],
        [ 0.64284392, -0.5112657 , -2.53507266,  0.42444107]]))

In [33]:
Z = np.dot(X, Y)


In [34]:
X.shape, Y.shape, Z.shape

((3, 5), (5, 4), (3, 4))

In [35]:
Z = X.dot(Y)

## How numpy arrays represent data
**Contiguous** arrays represent data as one long ravelled line in memory. It uses the **shape**, **stride** and **dtype** attributes to represent N-dimensional arrays.

In [51]:
A = np.arange(30).reshape(5, 6)

In [52]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [53]:
A.shape

(5, 6)

In [54]:
A.strides

(48, 8)

In [55]:
A.dtype

dtype('int64')

In [56]:
B = A.view()
B.shape = 30,

In [57]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [58]:
B[0] = 100
A

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29]])

From the last lines we infer that `B` points to the same data as `A`. As a matter of fact, we can obtain the exact memory address as follows (but this is not useful unless interacting with C code)

In [59]:
A.ctypes.data  # memory address of first data point

29905264

In [68]:
C = np.asfortranarray(A)
C.strides, A.strides

((8, 40), (48, 8))

In [62]:
D = C.view()
D.shape = 30,

AttributeError: incompatible shape for a non-contiguous array

In [63]:
from numpy.lib.stride_tricks import as_strided

In [65]:
D = as_strided(C, (30,), (8,))

In [67]:
C, D

(array([[100,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29]]),
 array([100,   6,  12,  18,  24,   1,   7,  13,  19,  25,   2,   8,  14,
         20,  26,   3,   9,  15,  21,  27,   4,  10,  16,  22,  28,   5,
         11,  17,  23,  29]))